# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data.xci
# IP: The module: 'wr_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data.xci
# IP: The module: 'wr_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/wr_data/wr_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
