######################################################################
#
# File name : tb_wave.do
# Created on: Tue Mar 20 16:49:35 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
