######################################################################
#
# File name : top_hdmi_out_wave.do
# Created on: Tue Mar 20 16:42:40 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
