# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/DDR3_HDMI/project_1/project_1.srcs/sources_1/ip/ram_2048x8/ram_2048x8.xci
# IP: The module: 'ram_2048x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/DDR3_HDMI/project_1/project_1.srcs/sources_1/ip/ram_2048x8/ram_2048x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_2048x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/DDR3_HDMI/project_1/project_1.srcs/sources_1/ip/ram_2048x8/ram_2048x8.xci
# IP: The module: 'ram_2048x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/DDR3_HDMI/project_1/project_1.srcs/sources_1/ip/ram_2048x8/ram_2048x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_2048x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
