# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6.xci
# IP: The module: 'fifo_ddr3_rd_p6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_rd_p6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_rd_p6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_rd_p6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6.xci
# IP: The module: 'fifo_ddr3_rd_p6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_rd_p6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_rd_p6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FPGA_VIVADO/FPGA_GBET/project_1/project_1.srcs/sources_1/ip/fifo_ddr3_rd_p6/fifo_ddr3_rd_p6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_rd_p6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
